import {
  getIssueReadiness,
  isPrdIssue,
  markAcceptanceCriteriaDoneInBody,
  parseBlockedBy,
  parseBlockerReferences,
  parsePrettierWarningFiles,
  type BlockerReference,
  type Issue,
} from './ralph';

function issue(body: string): Issue {
  return {
    number: 1,
    title: 'Build a vertical slice',
    body,
  };
}

describe('ralph issue classification', () => {
  test('detects PRD parent issues generated by the to-prd skill', () => {
    expect(
      isPrdIssue(
        issue(`
## Problem Statement

## Solution

## User Stories

## Implementation Decisions

## Testing Decisions
`)
      )
    ).toBe(true);
  });

  test('treats a to-issues Blocked by none section as unblocked', () => {
    expect(
      parseBlockedBy(
        issue(`
## What to build

Implement a narrow behavior.

## Blocked by

None - can start immediately
`)
      )
    ).toEqual({
      status: 'unblocked',
      blockers: [],
    });
  });

  test('parses same-repo, cross-repo, and GitHub URL blocker references', () => {
    expect(
      parseBlockerReferences(`
- #12
- owner/repo#34
- https://github.com/acme/app/issues/56
`)
    ).toEqual([
      {
        number: 12,
      },
      {
        repo: 'owner/repo',
        number: 34,
      },
      {
        repo: 'acme/app',
        number: 56,
      },
    ]);
  });

  test('skips issues with open blockers', async () => {
    await expect(
      getIssueReadiness(
        issue(`
## Blocked by

- #12
`),
        async () => ({
          state: 'OPEN',
          title: 'Still blocking',
        })
      )
    ).resolves.toEqual({
      ready: false,
      reason: 'blocked by open issue #12',
    });
  });

  test('allows issues whose blockers are closed', async () => {
    const resolvedBlockers: BlockerReference[] = [];

    await expect(
      getIssueReadiness(
        issue(`
## Blocked by

- #12
- owner/repo#34
`),
        async (blocker) => {
          resolvedBlockers.push(blocker);

          return {
            state: 'CLOSED',
          };
        }
      )
    ).resolves.toEqual({
      ready: true,
    });

    expect(resolvedBlockers).toEqual([
      {
        number: 12,
      },
      {
        repo: 'owner/repo',
        number: 34,
      },
    ]);
  });

  test('skips malformed blocker sections instead of implementing them', async () => {
    await expect(
      getIssueReadiness(
        issue(`
## Blocked by

- the onboarding foundation task
`)
      )
    ).resolves.toEqual({
      ready: false,
      reason: 'unparseable Blocked by section: - the onboarding foundation task',
    });
  });
});

describe('ralph verification helpers', () => {
  test('extracts Prettier warning files without treating the summary as a file', () => {
    expect(
      parsePrettierWarningFiles(`
[warn] assets/app.icon/icon.json
[warn] scripts/agent/ralph.ts
[warn] Code style issues found in the above files. Run Prettier with --write to fix.
`)
    ).toEqual(['assets/app.icon/icon.json', 'scripts/agent/ralph.ts']);
  });
});

describe('ralph issue updates', () => {
  test('marks unchecked acceptance criteria complete', () => {
    expect(
      markAcceptanceCriteriaDoneInBody(`
## Acceptance criteria

- [ ] First criterion
- [x] Already complete
1. [ ] Numbered criterion

## Blocked by

- [ ] This checkbox is not an acceptance criterion
`)
    ).toEqual({
      changed: true,
      body: `
## Acceptance criteria

- [x] First criterion
- [x] Already complete
1. [x] Numbered criterion

## Blocked by

- [ ] This checkbox is not an acceptance criterion
`,
    });
  });

  test('reports no change when acceptance criteria are already complete', () => {
    expect(
      markAcceptanceCriteriaDoneInBody(`
## Acceptance criteria

- [x] Criterion
`)
    ).toEqual({
      changed: false,
      body: `
## Acceptance criteria

- [x] Criterion
`,
    });
  });
});
